# platform :ios, '6.0'

target 'TimeImprint' do

pod "JDFPeekaboo"
pod 'PBJVision'
pod 'PBJVideoPlayer'
pod 'GPUImage'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJExtension'
pod "VKVideoPlayer", "~> 0.1.1"

end

